# Generated by Django 4.0.6 on 2022-10-25 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=20)),
                ('esPalindromo', models.BooleanField(default=False)),
                ('creacion', models.DateTimeField(default=datetime.datetime.now)),
                ('update', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
